### ISSUE TITLE
MacOS Monterey: couldn't load mod-specific d3xp.dylib (Resurrection of Evil)

### ISSUE THREAD

**Issue by mkrupczak3** [MacSourcePorts/dhewm3#1]
# Description

When trying to run Resurrection of Evil (`d3xp`) using the [signed build from macsourceports.com](https://macsourceports.com/) the following appears:

`WARNING: couldn't load mod-specific d3xp.dylib. defaulting to base game's library!`

...

`ERROR: Function 'map_erebus1::main' not found in script for 'call' key on worldspawn`

# Cause

The likely root cause of this issue is that d3xp.dylib is missing from the provided binary

On Ubuntu Linux this missing library can be obtained by installing the `dhewm3-d3xp` package, but no such equivalent is available on MacOS

[Previous discussion](https://github.com/dhewm/dhewm3/issues/334#issuecomment-735498093) in issue #334 suggests that this library can only be obtained by compiling from source, an operation which is technically prohibitive for most normal users

# Fix

`d3xp.dylib` should be included by default with Mac binaries of this source port. Users of other platforms (such as Linux) may benefit from the inclusion of this library as well

# See also:

https://github.com/dhewm/dhewm3/issues/452

**Comment by MacSourcePortsAdmin** [comment]
I've uploaded a new build, it includes the XP code. Check it out and see if it works for you.

https://macsourceports.com/game/doom3
https://github.com/MacSourcePorts/dhewm3/releases/download/1.5.1/dhewm3_notarized_2022-04-25.zip

**Comment by mkrupczak3** [comment]
Thanks, will take a look this evening

**Comment by mkrupczak3** [comment]
Confirmed Fixed in 1.5.2, Thanks!
<img width="1440" alt="Screen Shot 2022-04-25 at 3 32 17 PM" src="https://user-images.githubusercontent.com/25494111/165160853-2e0ccd05-6181-406a-a830-3add110f3e85.png">
