### ISSUE TITLE
Problems with fullscreen and in-game graphics settings

### ISSUE THREAD

**Issue by mkrupczak3** [MacSourcePorts/dhewm3#2]
# Environment: 
MacOS Monterey 12.3.1, M1 Apple Silicon Macbook Air 13" 2020

XQuarts 2.8.1

<img width="274" alt="Screen Shot 2022-04-25 at 3 20 53 PM" src="https://user-images.githubusercontent.com/25494111/165161354-bde9cbb2-1cb5-4207-bbd0-e7687385fd4d.png">

# Issue Description:

On MacOS Monterrey, game boots up fine but cannot enter full screen mode (either via `⌥ + return` shortcut, or in game settings)

Changes to resolution in-game settings fail to effect the next launch of the game if the game is exited normally. If it is forced closed with `⌘+Q`, changes to resolution take effect on the next launch (but fullscreen still does not work)

Attempts to change the `dhewm3.cfg` file to change resolution of the Window fail to take effect. Manual changes to the `DoomConfig.cfg` file also fail to take effect

Very surprised this port works as well as it does on Apple Silicon though

# Complicating factors:

It is possible that this author's environment is experiencing issues due to XQuartz installation. Could not be reproduced by @MacSourcePorts: https://github.com/dhewm/dhewm3/issues/276#issuecomment-1108894517

# See Also:
https://github.com/dhewm/dhewm3/issues/276#issuecomment-1108820650

**Comment by MacSourcePortsAdmin** [comment]
In your `~/Library/Application Support/dhewm3/base` folder, is `dhewm3.cfg` being rewritten on exit? As in, if you run the game and then exit, is the Date Modified timestamp updated with the current time?

**Comment by mkrupczak3** [comment]
# Initial
```
bobjoe@mighty-m1 base % pwd
/Users/bobjoe/Library/Application Support/dhewm3/base
bobjoe@mighty-m1 base % md5sum dhewm.cfg
51565e9ad121d9943a26eea102d68c59  dhewm.cfg
```

# Action: press `⌥ + return` while window selected
## Result: dhewm.cfg hash changes, window size reset to 640x480, no fullscreen
```
bobjoe@mighty-m1 base % md5sum dhewm.cfg
8119fc1d5b00d6b53a470ac9010c7c9b  dhewm.cfg
```

# Action: change screen resolution in in-game settings
## Result: dhewm.cfg hash changes as expected and remains the same after program is exited. Change is reflected correctly on next launch

```
bobjoe@mighty-m1 base % md5sum dhewm.cfg
8729b744a0dcf702707380d95c7b1844  dhewm.cfg
```

**Comment by mkrupczak3** [comment]
So it looks like I was mistaken on the nature of the issue; The in-game setting does work but it's actually the `⌥ + return` keypress sequence which was changing window size back to 640x480

**Comment by mkrupczak3** [comment]
Still, It looks like pixel size is being doubled on the Retina display. It may be possible to improve visual quality by allowing retina display high-dpi support

In addition, fullscreen still does not work on this build for me

**Comment by mkrupczak3** [comment]
Huh, fullscreen randomly just started to work, and persists across launches

I have no idea what fixed the issue. Can no longer reproduce

If this happens to someone else later, this is the sequence of events I did just before the issue corrected itself:

-  change the resolution from 640x480 to 800x600, apply changes, restart `dhewm3.app`, change to fullscreen, apply changes, restart `dhewm3.app` again, change resolution from 800x600 to 2560x1600, apply changes, restart `dhewm3.app` a final time

**Comment by mkrupczak3** [comment]
Thanks for taking a look anyways. This issue is closed, can no longer reproduce

**Comment by MacSourcePortsAdmin** [comment]
> ...randomly just started to work...
> ...I have no idea what fixed the issue...

If it's any consolation this is my experience with Mac game development in general :)
